### ISSUE TITLE
Meta Tags

### ISSUE THREAD

**Issue by jehoshua02** [deseretdigital-ui/CSS-Guidelines#21]
Loosely related with css is that in order for much of our CSS to work the way we want, we need these meta tags on every page:

``` html
  <meta http-equiv="x-ua-compatible" content="IE=edge">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
```

Should this be in the CSS Guides?

**Before Closing Issue:**
- [x] Response from @jstoutenburg
- [ ] Response from @janiv
- [ ] Response from @kbratko
- [ ] Response from @jspencerDDM
- [ ] Response from @hhatfield 
- [ ] Consensus or Decision
- [ ] Pull request or other action if necessary
